### ISSUE TITLE
Issue with redirect method.

### ISSUE THREAD

**Issue by noor-indglobal** [arif98741/nagadApi#2]
Hi there,
Good day 

I have check the above script script is working well but I found one issue with redirection 
instead of redirect can you please modify it to return the payment url for the same. Because script will be use only for one page.
if we need to use it for any rest API or graphQl with this SDK then it won't work.

So instead on redirecting user to payment page can the function return the url so we can use the code as per our requirement or you can set any parametre to return or redirect that will be good 

Above is my suggession only if you can make it then it will be great!

Thanks

**Comment by arif98741** [comment]
Thanks for your suggession. I really appreciate your concern about this nagad sdk. I will change and return redirect url so that any one can easily do whatever he/she wants !

**Comment by noor-indglobal** [comment]
Hi @arif98741 
Thanks for your upgrade it help now with rest API and graphQl as well 

Happy coding :)

**Comment by arif98741** [comment]
Thanks. Stay safe
Happy coding.
